# Ejemplos

POST http://localhost:3000/products/products HTTP/1.1
content-type: application/json

{ 
    "nombre": "Tomate", 
    "stock": 20 
}

### 

POST http://localhost:3000/products/products HTTP/1.1
content-type: application/json

{ 
    "nombre": "Pepinillo", 
    "stock": 21 
}

### 

GET http://localhost:3000/products/products HTTP/1.1
content-type: application/json

###

GET http://localhost:3000/products/products/6544f16661269657e5324e80 HTTP/1.1
content-type: application/json

###

PUT http://localhost:3000/products/products/655a9b3e8b8747bc6a13a543 HTTP/1.1
content-type: application/json

{ 
    "nombre": "Maiz", 
    "stock": 42
}

###

DELETE http://localhost:3000/products/products/6544f16661269657e5324e80 HTTP/1.1
content-type: application/json

###

DELETE https://nxapi-mongodb.vercel.app/products/products/6542da20c20d9ad95c739701 HTTP/1.1
content-type: application/json

### 

POST https://nxapi-mongodb.vercel.app/products/products HTTP/1.1
content-type: application/json

{ 
    "nombre": "Berenjena", 
    "stock": 21 
}

### 

DELETE https://nxapi-mongodb.vercel.app/products/products/6542da35c20d9ad95c739702
content-type: application/json
